spring:
  application:
    name: time-management-backend
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:timemanagement}
      # Configurações específicas para MongoDB Atlas no Render
      auto-index-creation: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.timemanagement: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR
    org.springframework.web: WARN
    org.mongodb.driver: WARN
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
