spring:
  application:
    name: time-management-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://d19spwebdeveloper:LkHq1PWi16m6o1Sh@cluster0.97xloha.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:timemanagement}
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.timemanagement: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR
    org.springframework.web: INFO
    org.mongodb.driver: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
